contact_links:
  - name: Help or Questions ğŸŒˆ
    url: https://github.com/fay-org/fect/discussions
    about: Issue does not support problem discussion. Please refer to the Github's Discussions ğŸ™.
